### ISSUE TITLE
CUL ESA1000 

### ISSUE THREAD

**Issue by x2ndstar** [Tommi2Day/ipsymcon-phpmodule-by-Tommi#2]
Hallo Tomas, 
ich habe dein Modul für das aktuelle IPSymcon eingerichtet, das geht alles Super. Beim CUL Modul wird aber die Leistung bei dem auslesen der ESA1000 Werte nicht ausgerechnet. Bei meiner Installation wird immer ein aktueller Wert von 0,0xxxx Watt raus. 

Ich denke hier müsste auch die Zeit zwischen den 2 Werten (aktuell und der letzte) als Parameter zum Teilen der Ticks um die aktuelle Leistung anzuzeigen, 
if ($ticks > 0) {
            $data['TPower'] = $total_cnt / $ticks;
            $data['APower'] = $current_cnt / $ticks;
        }

greetings Rüdiger

**Comment by Tommi2Day** [comment]
TPower und APower sind hier absolute Werte in Watt. Leider hat jeder Gerätehersteller und insbesondere auch ELV eigene Vorstellungen auf welchen Zeitraum sich die angezeigten Werte beziehen, so das eine Leistungsanzeige wie W/h für mich bisher nicht umsetzbar war. Zudem habe ich auch kein Gerät zum Testen. Die mir bekannte Definition ist 

> $current_cnt: current value (average over latest 5 minutes) in device units

Demnach sollte der angezeigte für dieses Gerät APower*12 den Wert in W/h liefern. Bei anderen Sensoren der Baureihe ist das wohl leider wieder anders.
