### ISSUE TITLE
EnergyModul

### ISSUE THREAD

**Issue by Nisbo** [Tommi2Day/ipsymcon-phpmodule-by-Tommi#3]
Looks like there is a Problem with the EnergyModul in IPS 5.0

https://www.youtube.com/watch?v=z74LRvRmHA8&feature=youtu.be
![screenshot_957](https://user-images.githubusercontent.com/26260572/44003265-2d0ff0d6-9e50-11e8-8f9b-77e83dc658fe.jpg)
![screenshot_958](https://user-images.githubusercontent.com/26260572/44003266-3027cb5e-9e50-11e8-9cb1-a5cd986ebec4.jpg)

Disregard the 2nd image with the "Rechen-Modul", I can not remove it from my comment

**Comment by Tommi2Day** [comment]
yes, i know. My modules are currently  not ready for 5.0 (as is it indicated by the branch) This will take some time

**Comment by Nisbo** [comment]
How can I disable the module / this part of the module ? 
Or do I have to remove the module from the module list ?
In this case I expect some unexpected behaviour in IPS because I don't know which parts are used in my project ^^

**Comment by Tommi2Day** [comment]
unfortunally, you need to remove the whole set of my modules by dropping the repo entry in module control .. or try to fix the syntax issues which came up with the new version. Its plain text :) In the particular case change the "~string" profile entries to an empty profile in module.php. This profile has been removed by the IPS guys

**Comment by Tommi2Day** [comment]
Modules has been updated for IPS5.0. Pls change module branch to 5.0 and try it out

**Comment by Nisbo** [comment]
super
