### ISSUE TITLE
Modul OWN don‘t work with IPS 7.0

### ISSUE THREAD

**Issue by TissenMi** [Tommi2Day/ipsymcon-phpmodule-by-Tommi#4]
Hi Thommy,

Will you please check, in your own Modul will work with IPS 7. The Connection to the OW-Server is ok, but there no aktuell Data‘s and it comes an error. 

Thanks and beste Grüße 
Michael

**Comment by Tommi2Day** [comment]
Hi,

the problem here is the complete outdated ownet php library from owfs project (https://www.owfs.org/index_php_page_ownet-php.html). It needs an adoption to PHP8. I dont expect this from the project itself, maybe you know another source or can provide a PR 

Tommi

**Comment by Tommi2Day** [comment]
I made a fixed version which works for me. Pls Change the module branch to 7.0 and reload. Your  feedback is very welcome

Tommi

**Comment by Tommi2Day** [comment]
Fixed in Build 7001
